package routes

import (
	"go-skeleton-rest-app/pkg/handlers"

	"github.com/labstack/echo/v4"

	echoSwagger "github.com/swaggo/echo-swagger"
	_ "go-skeleton-rest-app/docs" // docs generated by Swag CLI, you have to import it.
)

// define your URL path here
const (
	PATH_HOME         = "/"
	PATH_HEALTH_CHECK = "/healthcheck"
)

func InitRoutes(e *echo.Echo) {

	// divide each handler to individual .go file.

	e.GET(PATH_HOME, handlers.Home)                // home.go
	e.GET(PATH_HEALTH_CHECK, handlers.HealthCheck) // healthcheck.go

	// Swagger docs route
	e.GET("/docs/*", echoSwagger.WrapHandler)

}
