package routes

import (
	"go-skeleton-rest-app/pkg/handlers"

	"github.com/labstack/echo/v4"

	_ "go-skeleton-rest-app/docs" // docs generated by Swag CLI, you have to import it.

	echoSwagger "github.com/swaggo/echo-swagger"
)

// define your URL path here
const (
	PATH_HOME                     = "/"
	PATH_HEALTH_CHECK             = "/healthcheck"
	PATH_LIST_CITIES              = "/cities"
	PATH_LIST_CITIES_BY_COUNTRYID = "/citiesbycountryid/:id"
	PATH_POST_CITY                = "/postcity/:city/:id"
	PATH_PUT_CITY_BY_COUNTRYID    = "/updatecity/:city/:id"
	PATH_DELETE_CITY_BY_CITYNAME  = "/deletecity/:city"
)

func InitRoutes(e *echo.Echo) {

	// divide each handler to individual .go file.

	// route to handler
	e.GET(PATH_HOME, handlers.Home)                // home.go
	e.GET(PATH_HEALTH_CHECK, handlers.HealthCheck) // healthcheck.go
	e.GET(PATH_LIST_CITIES, handlers.ListCities)
	e.GET(PATH_LIST_CITIES, handlers.ListCities)
	e.GET(PATH_LIST_CITIES_BY_COUNTRYID, handlers.ListCitiesByCountryId)
	e.POST(PATH_POST_CITY, handlers.CreateCity)
	e.PUT(PATH_PUT_CITY_BY_COUNTRYID, handlers.UpdateCity)
	e.DELETE(PATH_DELETE_CITY_BY_CITYNAME, handlers.DeleteCity)
	// Swagger docs route
	e.GET("/docs/*", echoSwagger.WrapHandler)

}
